.PHONY:clean
all:
	g++ -c Like_terminal.cpp -o Like_terminal.o && sudo mkdir /usr/local/include/sakamoto && sudo mkdir /usr/local/lib/sakamoto && sudo mkdir /usr/local/bin/sakamoto

clean:
		sudo rm -rf /usr/local/bin/sakamoto /usr/local/include/sakamoto /usr/local/lib/sakamoto && rm Like_terminal.o 
