.PHONY:clean
all:
	g++ -c Like_terminal.cpp -o Like_terminal.o && sudo mkdir /usr/local/include/arc && sudo mkdir /usr/local/lib/arc && sudo mkdir /usr/local/bin/arc

clean:
		sudo rm -rf /usr/local/bin/arc /usr/local/include/arc /usr/local/lib/arc && rm Like_terminal.o 
